{% set name = "boutdata" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1ca3a3798d53a7c980b8e30d7412503135ab25990af2042900e2606e5f281ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - sympy
    - numpy
    - matplotlib-base
    - scipy
    - boututils

test:
  imports:
    - boutdata
  requires:
    - pytest
  commands:
    - bout-squashoutput --help
    - pytest --pyargs boutdata

about:
  home: https://github.com/boutproject/boutdata
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Load and plot BOUT++ output data
  description: |
    pip-package of what was previously found in BOUT-dev/tools/pylib/boutdata
    Note that BOUT-dev/tools/pylib/boutdata will likely be replaced by this
    repo in BOUT++ v4.4.0.
    > **NOTE**: This package will likely be superseded by xBOUT in the near future
  dev_url: https://github.com/boutproject/boutdata

extra:
  recipe-maintainers:
    - johnomotani
    - ZedThree
    - loeiten
