{% set name = "boutdata" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 043cddaeb38b128d2525f2005f48a5b7717ff5832a932183a4bef1d3eae389e0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - sympy
    - numpy
    - matplotlib-base
    - natsort
    - scipy
    - boututils

test:
  imports:
    - boutdata
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - bout-squashoutput --help
    - pytest --pyargs boutdata

about:
  home: https://github.com/boutproject/boutdata
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Load and plot BOUT++ output data
  description: |
    pip-package of what was previously found in BOUT-dev/tools/pylib/boutdata
    Note that BOUT-dev/tools/pylib/boutdata will likely be replaced by this
    repo in BOUT++ v4.4.0.
    > **NOTE**: This package will likely be superseded by xBOUT in the near future
  dev_url: https://github.com/boutproject/boutdata

extra:
  recipe-maintainers:
    - johnomotani
    - ZedThree
    - loeiten
